#spring
spring:
  #datasource
  datasource:
    url: jdbc:mysql://localhost/emoji?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
  #JPA
  jap:
    show-sql: true
    hibernate:
      ddl-auto: update


  #thymeleaf
  thymeleaf:
          prefix: classpath:/templates/
          suffix: .html
          mode: HTML5
          encoding: UTF-8
          content-type: text/html; charset=utf-8
          cache: false

